version: '3.9'

services:
  api:
    build: .
    container_name: remote_nomads_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app   # optional, for live reload in development
